=== tcatapano/GR8975-edition/_site/schema/testentry.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT entry (#PCDATA|activity|block|figure|folio|heading|purpose|annotations|list|margin-block)*>
<!ATTLIST entry
  group NMTOKEN #IMPLIED
  identifier NMTOKEN #REQUIRED>

<!ELEMENT entry_group (folio,(block|heading)+)>
<!ATTLIST entry_group
  identifier NMTOKEN #REQUIRED>

<!ELEMENT annotations (annotation)>
<!ATTLIST annotations
  >


<!ELEMENT list (foreign|item+)>
<!ATTLIST list  
  purpose NMTOKEN #IMPLIED>

<!ELEMENT margin-block (#PCDATA|animal|material|tool)*>
<!ATTLIST margin-block
  position NMTOKEN #REQUIRED
  purpose CDATA #IMPLIED>

<!ELEMENT annotation EMPTY>
<!ATTLIST annotation  
  title CDATA #REQUIRED
  url CDATA #REQUIRED>


<!ELEMENT personal_name (#PCDATA)>
<!ATTLIST personal_name
  >

<!ELEMENT figure EMPTY>
<!ATTLIST figure
  identifier NMTOKEN #IMPLIED
  number NMTOKEN #IMPLIED
  position NMTOKEN #IMPLIED
  url CDATA #IMPLIED>

<!ELEMENT heading (#PCDATA|color|foreign|material|material_format|plant
                   |profession|tool)*>
<!ATTLIST heading
  position NMTOKEN #IMPLIED>

<!ELEMENT purpose (#PCDATA|activity|color|currency|material
                   |material_format|place|plant|profession|ref
                   |sub_recipe|time|tool|unit)*>
<!ATTLIST purpose
  type NMTOKEN #REQUIRED>

<!ELEMENT profession (#PCDATA)>
<!ATTLIST profession
  >

<!ELEMENT place (#PCDATA)>
<!ATTLIST place
  >

<!ELEMENT folio EMPTY>
<!ATTLIST folio
  number NMTOKEN #IMPLIED
  url CDATA #IMPLIED>

<!ELEMENT block (#PCDATA|activity|animal|color|currency|figure|foreign
                 |material|material_format|place|plant|profession
                 |purpose|ref|sub_recipe|time|tool|unit
                 |name|note|people|q|sup)*>
<!ATTLIST block
  identifier NMTOKEN #IMPLIED
  location NMTOKEN #IMPLIED
  position NMTOKEN #IMPLIED
  purpose CDATA #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
    type NMTOKEN #REQUIRED>

<!ELEMENT note (#PCDATA)>
<!ATTLIST note
  >

<!ELEMENT people (#PCDATA)>
<!ATTLIST people
  >

<!ELEMENT q (foreign)>
<!ATTLIST q
  >

<!ELEMENT sup (#PCDATA|material)*>
<!ATTLIST sup
  >

<!ELEMENT material (#PCDATA|animal|color|foreign|place|plant
                    |profession)*>
<!ATTLIST material
  type NMTOKEN #IMPLIED>

<!ELEMENT animal (#PCDATA)>
<!ATTLIST animal
  >

<!ELEMENT tool (#PCDATA|foreign|material|material_format|plant|tool)*>
<!ATTLIST tool
  >

<!ELEMENT item (#PCDATA|material|tool|unit)*>
<!ATTLIST item
  >

<!ELEMENT foreign (#PCDATA|item)*>
<!ATTLIST foreign
  language NMTOKEN #IMPLIED>

<!ELEMENT material_format (#PCDATA|color|material)*>
<!ATTLIST material_format
  >

<!ELEMENT color (#PCDATA)>
<!ATTLIST color
  >

<!ELEMENT plant (#PCDATA|foreign)*>
<!ATTLIST plant
  >

<!ELEMENT sub_recipe (#PCDATA|material|tool)*>
<!ATTLIST sub_recipe
  type NMTOKEN #IMPLIED>

<!ELEMENT activity (#PCDATA|material)*>
<!ATTLIST activity
  type CDATA #REQUIRED>

<!ELEMENT unit (#PCDATA|tool)*>
<!ATTLIST unit
  >

<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref
  identifier NMTOKEN #IMPLIED
  type NMTOKEN #IMPLIED>

<!ELEMENT currency (#PCDATA)>
<!ATTLIST currency
  >

<!ELEMENT time (#PCDATA)>
<!ATTLIST time
  >

=== tcatapano/GR8975-edition/_site/xml/p039r_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entry SYSTEM "../schema/testentry.dtd">
<entry identifier="p039r_2">
    <folio number="039r" url="http://gallica.bnf.fr/ark:/12148/btv1b10500001g/f83.image"/>
    <purpose type="observation"/>
    <purpose type="making"/>
    <heading>Dyers’ woad</heading>
    <block> It is grown in <place>Lauragais</place> where the deep soil is so fertile that every
        year wheat was grown there, it would lie flat for being too vigorous. This is why dyers’
        woad and wheat are grown there alternately. For cultivating dyers’ woad, the soil is
        ploughed with <tool>iron shovels</tool>, as gardeners do. Next, it is harrowed with
            <tool>rakes</tool>, &amp; broken up finely as for sowing some kitchen herbs. It is
        commonly sown on Saint Anthony's day in January. Eight harvests are made. The first ones are
        better. The best dyers’ woad of Lauragais is the one from <place>Carmail</place> &amp; the
        one from <place>Auragne</place>. And sometimes the dyers’ woad is good in one field &amp; in
        the one close by it will hardly have worth. The goodness of the dyers’ woad can be
        recognized when put in the mouth it gives the taste of vinegar, or when crumbling &amp;
        breaking it, it has some mold-like veins which are as it were golden or silver. It is
        assayed in the <tool>dyers' vat</tool>, and to fill a vat with it, six bales of it are
        needed. There several flocks of <material>wool</material> are dyed, and if it dyes fifteen
        times, it is said to be worth 15 florins, if it gives xx dyings, xx florins. The good kind
        dyes up to 30 times &amp; commonly up to xxv or 26.</block>
</entry>

=== tcatapano/GR8975-edition/xml/p040v_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entry SYSTEM "../schema/testentry.dtd">
<entry identifier="p040v_02">
    <folio number="040v" url="http://gallica.bnf.fr/ark:/12148/btv1b10500001g/f86.image"/>
    <purpose type="observation"/>
    <heading>Latten and calamine</heading>
    <block>Founders do not melt latten in a <tool>bellow furnace</tool> but in
            <tool>crucibles</tool>, for in a bellow furnace and amid the
            <material>charcoals</material>, the <material>calamine</material> would
        disappear.</block>
</entry>

=== tcatapano/GR8975-edition/xml/p040r_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entry SYSTEM "../schema/testentry.dtd">
<entry identifier="p040r_3">
    <folio number="040r" url="hhttp://gallica.bnf.fr/ark:/12148/btv1b10500001g/f85.image"/>
    <purpose type="making"/>
    <purpose type="observation"/>
    <heading>Vinegar</heading>
    <block>One takes for granted that jec heat red-hot the <material>mineral salt</material> that
        looks like <material>marble</material> &amp; that is called in <place>Catalonia</place>
        &amp; at the border of <place>Spain</place>
        <material>Cardana salt</material>C, &amp; throwing it in the red hot or quite hot in
            <material>wine</material>, it turns it into very good <material>vinegar</material>. Some
        make it with <material>water</material> poured on <material>pomace</material> soured after
        being pressed by <tool>grape pickers</tool>, but it will not keep &amp; spoils in heat &amp;
        thunder storms.</block>
</entry>

=== tcatapano/GR8975-edition/xml/p040r_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entry SYSTEM "../schema/testentry.dtd">
<entry identifier="p040r_5">
    <folio number="040r" url="hhttp://gallica.bnf.fr/ark:/12148/btv1b10500001g/f85.image"/>
    <purpose type="observation"/>
    <heading>Grottos</heading>
    <block>To fill some empty place that cannot be laden with hanging rocks, one puts a piece of
        thick <material>parchment</material> close to the fire, which shrinks &amp; crumples. Then
        one paints it with <material>distemper</material>, then in <material>oil</material>. Next
        one affixes it.</block>
</entry>

=== tcatapano/GR8975-edition/xml/p040r_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entry SYSTEM "../schema/testentry.dtd">
<entry identifier="p040r_4">
    <folio number="040r" url="hhttp://gallica.bnf.fr/ark:/12148/btv1b10500001g/f85.image"/>
    <purpose type="observation"/>
    <purpose type="application"/>
    <heading>Silver gilt buttons</heading>
    <block>Because <material>silver gilt</material> does not fear fire, it is cut into lozenges
        flat[illegible] on one side, then they are joined together in a star shape with a paste of
            <material>crushed enamel</material>, which is then melted &amp; the enamel is gilt with
        <material>gold leaf</material> and then reheated.</block>
</entry>

=== tcatapano/GR8975-edition/xml/p041v_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entry SYSTEM "../schema/testentry.dtd">
<entry identifier="p041v_1">
    <folio number="041v" url="http://gallica.bnf.fr/ark:/12148/btv1b10500001g/f88.image"/>
    <purpose type="observation"/>
    <heading>Glassmaker's black</heading>
    <block>Filings of <material>iron</material> taken from bars that have been in the fire for a
        long time, which are thick, are much better than the common soft ones that fall under the
            <tool>anvil</tool> in the <tool>forge</tool>, because they imitate niello. To said
        black, described elsewhere, some people add a little <material>minium</material>.</block>
</entry>

=== tcatapano/GR8975-edition/xml/p039r_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entry SYSTEM "../schema/testentry.dtd">
<entry identifier="p039r_1">
    <folio number="039r" url="http://gallica.bnf.fr/ark:/12148/btv1b10500001g/f83.image"/>
    <purpose type="observation"/>
    <heading>Goldsmith</heading>
    <block> They bind <material>silver filings</material> with <material>saltpeter</material> which
        refines it &amp; does not make it brittle. But <material>gold filings</material> are bound
        with <material>borax</material> or, to save the borax, with <material>lead</material>, which
        refines the gold &amp; softens it, for the saltpeter would make it brittle, which it does
        not do to silver. This is why, in order to save, goldsmiths use it to bind it in order to
        save borax, which costs viii sols per ounce &amp; saltpeter costs x sols per lb. When
        goldsmiths have thus bound their silver filings with salpeter, a red enamel vitrifies at the
        bottom of the crucible. I do not know if the <material>copper</material> mixed in with the
        silver is the cause for this. Try for enamel.</block>
</entry>
